#!/usr/bin/env python3
"""Create and verify a participant's Module 1 workspace.

The workspace IS the lab root — the folder they opened VS Code in. That matters: project
configuration (`.claude/`, `CLAUDE.md`) is loaded from the project root, so putting their
work in a subfolder would mean nothing they write in Module 1 actually takes effect without
starting a second session somewhere else.

    workspace.py stage m1s1-harness                apply one incremental stage
    workspace.py catchup                           replay applied stages, repairing the lab's files
    workspace.py setup --track support-triage       copy the whole track payload in
    workspace.py verify                             is the workspace intact?
    workspace.py manifest --track <id>              what a setup would create

Refuses to overwrite existing work unless --force. Stdlib only.
"""

from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys

PLUGIN_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TRACKS_DIR = os.path.join(PLUGIN_ROOT, "tracks")
STAGES_DIR = os.path.join(PLUGIN_ROOT, "stages")

WORKSPACE_GITIGNORE = """\
# Environment report — regenerated by /lab:doctor, not worth versioning
.agent-lab/doctor.json

# Python
__pycache__/
*.py[cod]
.venv/
venv/

# Vector store — rebuilt from data/ in Module 2
chroma/
.chroma/

.DS_Store
"""


def payload_dir(track: str) -> str:
    path = os.path.join(TRACKS_DIR, track, "workspace")
    if not os.path.isdir(path):
        sys.exit(f"track '{track}' has no workspace payload at {path}")
    return path


def payload_files(track: str) -> list[str]:
    """Every file the payload would install, as paths relative to the lab root."""
    root = payload_dir(track)
    out = []
    for dirpath, _dirnames, filenames in os.walk(root):
        for name in filenames:
            if name == ".DS_Store":
                continue
            full = os.path.join(dirpath, name)
            out.append(os.path.relpath(full, root))
    return sorted(out)


def record_stage(root: str, stage_id: str) -> None:
    """Remember which stages have been applied, in order, so catchup can replay them."""
    state_file = os.path.join(root, ".agent-lab", "state.json")
    if not os.path.exists(state_file):
        return
    try:
        with open(state_file) as fh:
            state = json.load(fh)
    except (OSError, ValueError):
        return
    progress = state.setdefault("progress", {})
    applied = progress.setdefault("applied_stages", [])
    if stage_id not in applied:
        applied.append(stage_id)
    tmp = state_file + ".tmp"
    with open(tmp, "w") as fh:
        json.dump(state, fh, indent=2)
        fh.write("\n")
    os.replace(tmp, state_file)


def record_installed(root: str, files: list[str]) -> None:
    """Remember what has been installed so far.

    `verify` used to compare against a track's whole payload, which meant a perfectly
    healthy stage-1 workspace was reported as missing fourteen files. It checks this
    instead: what the lab actually put there.
    """
    state_file = os.path.join(root, ".agent-lab", "state.json")
    if not os.path.exists(state_file):
        return
    try:
        with open(state_file) as fh:
            state = json.load(fh)
    except (OSError, ValueError):
        return
    progress = state.setdefault("progress", {})
    known = set(progress.get("installed_files") or [])
    known.update(files)
    progress["installed_files"] = sorted(known)
    tmp = state_file + ".tmp"
    with open(tmp, "w") as fh:
        json.dump(state, fh, indent=2)
        fh.write("\n")
    os.replace(tmp, state_file)


def _git(args: list[str], cwd: str) -> tuple[int, str]:
    """Run git, supplying an identity only if the machine has none configured."""
    base = ["git"]
    code, _ = _run(["git", "config", "user.email"], cwd)
    if code != 0:
        base += ["-c", "user.email=participant@agent-lab.local",
                 "-c", "user.name=Agent Lab Participant"]
    return _run(base + args, cwd)


def _run(cmd: list[str], cwd: str) -> tuple[int, str]:
    try:
        p = subprocess.run(cmd, cwd=cwd, capture_output=True, text=True, timeout=60)
        return p.returncode, (p.stdout + p.stderr).strip()
    except (OSError, subprocess.SubprocessError) as exc:
        return 1, str(exc)


def track_meta(track: str) -> dict:
    path = os.path.join(TRACKS_DIR, track, "track.json")
    if not os.path.exists(path):
        sys.exit(f"unknown track '{track}'")
    with open(path) as fh:
        return json.load(fh)


def cmd_stage(args) -> int:
    """Apply one incremental stage: a little more workspace, a little more capability.

    Stages exist so the participant never receives a finished environment. Each one adds
    only what the next experiment needs, and the diff between two stages is small enough
    to read.
    """
    root = os.path.abspath(args.root)
    stage_dir = os.path.join(STAGES_DIR, args.stage_id)
    meta_path = os.path.join(stage_dir, "stage.json")
    if not os.path.exists(meta_path):
        available = sorted(os.listdir(STAGES_DIR)) if os.path.isdir(STAGES_DIR) else []
        sys.exit(f"unknown stage '{args.stage_id}' — available: {', '.join(available)}")
    with open(meta_path) as fh:
        stage = json.load(fh)

    track = args.track
    if not track:
        state = os.path.join(root, ".agent-lab", "state.json")
        if os.path.exists(state):
            with open(state) as fh:
                track = json.load(fh).get("track")
    if not track:
        sys.exit("no track known — pass --track or run /lab:start first")

    meta = track_meta(track)
    key_files = meta.get("key_files") or {}
    # Stage payloads are shared by every track, so anything track-specific in them is a
    # placeholder resolved from track.json. Forgetting one ships the lead track's task to
    # every group, which is exactly the bug this replaced.
    substitutions = {
        "{{FIRST_INPUT}}": meta.get("first_input", ""),
        "{{FIRST_TASK}}": meta.get("first_task", ""),
        "{{SKILL_NAME}}": meta.get("first_skill", ""),
        "{{TOOL_NAME}}": meta.get("first_tool", ""),
        "{{TOOL_COMMAND}}": meta.get("tool_command", ""),
        "{{TOOL_PURPOSE}}": meta.get("tool_purpose", ""),
        "{{OUTPUT_DIR}}": meta.get("output_dir", ""),
        "{{SYSTEM_NAME}}": meta.get("system_name", ""),
        "{{TEMPTING_WRITE_TASK}}": meta.get("tempting_write_task", ""),
        "{{GENERAL_QUESTION}}": meta.get("general_question", ""),
        "{{UNKNOWN_ITEM}}": meta.get("unknown_item", ""),
        "{{OUTPUT_FORMAT_FILE}}": key_files.get("output_format", ""),
        "{{POLICY_FILE}}": key_files.get("policy", ""),
    }

    def fill(text: str) -> str:
        for token, value in substitutions.items():
            text = text.replace(token, value)
        return text

    written = []

    # 1. stage-provided files, with placeholders resolved in text files
    files_root = os.path.join(stage_dir, "files")
    if os.path.isdir(files_root):
        for dirpath, _dirs, names in os.walk(files_root):
            for name in names:
                if name == ".DS_Store":
                    continue
                src = os.path.join(dirpath, name)
                rel = os.path.relpath(src, files_root)
                dst = os.path.join(root, rel)
                os.makedirs(os.path.dirname(dst), exist_ok=True)
                if name.endswith((".md", ".json", ".txt", ".prompt", ".yaml", ".yml")):
                    with open(src) as fh:
                        open(dst, "w").write(fill(fh.read()))
                else:
                    shutil.copy2(src, dst)
                written.append(rel)

    # 2. settings.json, only when the stage supplies one
    if stage.get("settings"):
        dst = os.path.join(root, ".claude", "settings.json")
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        shutil.copy2(os.path.join(stage_dir, stage["settings"]), dst)
        written.append(".claude/settings.json")

    # 3. the tracer becomes THEIR file, in THEIR repo, so they can read it
    if stage.get("install_tracer"):
        dst = os.path.join(root, ".claude", "hooks", "trace.py")
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        shutil.copy2(os.path.join(PLUGIN_ROOT, "scripts", "trace.py"), dst)
        os.chmod(dst, 0o755)
        written.append(".claude/hooks/trace.py")

    # 5. data pulled from the track, only what this stage needs.
    #    "{{ALL}}" means the rest of the corpus — used once the exercises need it all.
    wanted = []
    for entry in stage.get("from_track", []):
        wanted.extend(payload_files(track) if entry == "{{ALL}}" else [entry])
    for rel in wanted:
        rel = fill(rel)
        src = os.path.join(payload_dir(track), rel)
        if not os.path.exists(src):
            sys.exit(f"stage wants '{rel}' from track '{track}', which does not have it")
        dst = os.path.join(root, rel)
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        shutil.copy2(src, dst)
        written.append(rel)

    # 6. files copied straight out of the plugin. Used for things that must exist in the
    #    participant's own folder — the handbook, so it is reachable without a browser
    #    leaving their network — while living in exactly one place in the repo.
    for source, dest in (stage.get("plugin_files") or {}).items():
        src = os.path.join(PLUGIN_ROOT, source)
        if not os.path.exists(src):
            sys.exit(f"stage wants plugin file '{source}', which this plugin does not have")
        rel = fill(dest)
        dst = os.path.join(root, rel)
        os.makedirs(os.path.dirname(dst) or root, exist_ok=True)
        shutil.copy2(src, dst)
        written.append(rel)

    # 7. per-track scaffolds: starter files that differ by track, so they cannot live in
    #    the shared stage payload. Never overwrite one the participant has started editing.
    for source, dest in (stage.get("scaffolds") or {}).items():
        src = os.path.join(TRACKS_DIR, track, "scaffolds", source)
        if not os.path.exists(src):
            sys.exit(f"stage wants scaffold '{source}' for track '{track}', "
                     f"which does not have it")
        rel = fill(dest)
        dst = os.path.join(root, rel)
        if os.path.exists(dst):
            continue
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        with open(src) as fh:
            content = fill(fh.read())
        with open(dst, "w") as fh:
            fh.write(content)
        os.chmod(dst, 0o755)
        written.append(rel)

    for d in ("notes",):
        os.makedirs(os.path.join(root, d), exist_ok=True)

    git_note = "no git repository — checkpoints will not work"
    if not os.path.isdir(os.path.join(root, ".git")):
        code, _ = _git(["init", "-q"], root)
        git_note = "git repository initialised" if code == 0 else "git init failed"
    if os.path.isdir(os.path.join(root, ".git")):
        _git(["add", "-A"], root)
        code, out = _git(["commit", "-q", "-m", stage.get("commit", f"Stage {stage.get('stage')}")], root)
        git_note = "committed" if code == 0 else (
            "nothing new to commit" if "nothing to commit" in out else f"commit failed: {out[:80]}")

    record_installed(root, written)
    record_stage(root, stage["id"])

    print(json.dumps({
        "stage": stage.get("stage"), "id": stage["id"], "title": stage.get("title"),
        "track": track, "written": written, "git": git_note,
    }, indent=2))
    return 0


def cmd_manifest(args) -> int:
    files = payload_files(args.track)
    if args.as_json:
        print(json.dumps({"track": args.track, "files": files}, indent=2))
    else:
        for f in files:
            print(f)
        print(f"\n{len(files)} files, plus notes/ .claude/ .gitignore and a git repository")
    return 0


def cmd_setup(args) -> int:
    root = os.path.abspath(args.root)
    src = payload_dir(args.track)

    # Never clobber work in progress.
    if not args.force:
        collisions = [f for f in payload_files(args.track)
                      if os.path.exists(os.path.join(root, f))]
        if collisions:
            print(f"workspace already set up ({len(collisions)} existing files, "
                  f"e.g. {collisions[0]}) — nothing changed", file=sys.stderr)
            print("re-run with --force only if you mean to discard local changes",
                  file=sys.stderr)
            return 2

    created = []
    for rel in payload_files(args.track):
        dst = os.path.join(root, rel)
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        shutil.copy2(os.path.join(src, rel), dst)
        created.append(rel)

    for d in ("notes", ".claude"):
        os.makedirs(os.path.join(root, d), exist_ok=True)

    keep = os.path.join(root, "notes", ".gitkeep")
    if not os.path.exists(keep):
        open(keep, "w").close()

    gitignore = os.path.join(root, ".gitignore")
    if not os.path.exists(gitignore):
        with open(gitignore, "w") as fh:
            fh.write(WORKSPACE_GITIGNORE)
        created.append(".gitignore")

    # git: the checkpoint mechanism depends on it
    git_status = "already a git repository"
    if not os.path.isdir(os.path.join(root, ".git")):
        code, out = _git(["init", "-q"], root)
        if code != 0:
            print(f"warning: git init failed: {out}", file=sys.stderr)
            git_status = "git init FAILED — checkpoints will not work"
        else:
            git_status = "git repository initialised"

    if os.path.isdir(os.path.join(root, ".git")):
        _git(["add", "-A"], root)
        code, out = _git(["commit", "-q", "-m", "Module 1 starting state"], root)
        if code == 0:
            git_status += ", starting state committed"
        elif "nothing to commit" in out:
            git_status += ", nothing new to commit"
        else:
            git_status += f", commit failed: {out.splitlines()[0] if out else '?'}"

    record_installed(root, created)

    print(json.dumps({
        "track": args.track,
        "root": root,
        "files_created": len(created),
        "directories": sorted({os.path.dirname(f) for f in created if os.path.dirname(f)}),
        "git": git_status,
    }, indent=2))
    return 0


def cmd_catchup(args) -> int:
    """Restore the lab-provided parts of the workspace.

    Replays every stage already applied, in order. Stage payloads are the lab's files —
    settings, the tracer, the experiment runner and prompts — so replaying them repairs
    anything deleted or broken without touching the participant's own work.

    --with-reference additionally drops in the track's reference skill. That is the rescue
    for a participant stuck partway through writing their own: it is the answer key, so use
    it when someone would otherwise be stranded, not by default.
    """
    root = os.path.abspath(args.root)
    state_file = os.path.join(root, ".agent-lab", "state.json")
    if not os.path.exists(state_file):
        sys.exit("no lab state here — run /lab:start first")
    with open(state_file) as fh:
        state = json.load(fh)
    track = state.get("track")
    if not track:
        sys.exit("no track chosen yet — run /lab:start first")

    applied = (state.get("progress") or {}).get("applied_stages") or []
    if not applied:
        sys.exit("no stages applied yet — nothing to restore. Run /lab:next to begin.")

    replayed = []
    for stage_id in applied:
        result = subprocess.run(
            [sys.executable, os.path.abspath(__file__), "--root", root, "stage", stage_id],
            capture_output=True, text=True)
        replayed.append({"stage": stage_id,
                         "ok": result.returncode == 0,
                         "error": result.stderr.strip()[:200] or None})

    meta = track_meta(track)
    reference = None
    skill = meta.get("first_skill")
    src = os.path.join(TRACKS_DIR, track, "reference", "skills", skill)
    if args.with_reference:
        if os.path.isdir(src):
            dst = os.path.join(root, ".claude", "skills", skill)
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            if os.path.isdir(dst):
                shutil.rmtree(dst)
            shutil.copytree(src, dst)
            reference = f".claude/skills/{skill}/SKILL.md"
        else:
            reference = f"NOT AVAILABLE — no reference skill for track '{track}'"

    reference_tool = None
    if args.with_reference:
        tool = meta.get("first_tool")
        tool_src = os.path.join(TRACKS_DIR, track, "reference", "tools", f"{tool}.py")
        if tool and os.path.exists(tool_src):
            dst = os.path.join(root, "tools", f"{tool}.py")
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            shutil.copy2(tool_src, dst)
            os.chmod(dst, 0o755)
            reference_tool = f"tools/{tool}.py"

    reference_hook = None
    hook_src = os.path.join(TRACKS_DIR, track, "reference", "hooks", "write_boundary.py")
    reference_project = []
    if args.with_reference:
        if os.path.exists(hook_src):
            dst = os.path.join(root, ".claude", "hooks", "write_boundary.py")
            os.makedirs(os.path.dirname(dst), exist_ok=True)
            shutil.copy2(hook_src, dst)
            reference_hook = ".claude/hooks/write_boundary.py"
        project_src = os.path.join(TRACKS_DIR, track, "reference", "project")
        if os.path.isdir(project_src):
            for name in sorted(os.listdir(project_src)):
                shutil.copy2(os.path.join(project_src, name), os.path.join(root, name))
                reference_project.append(name)

    print(json.dumps({"track": track, "replayed": replayed,
                      "reference_skill": reference,
                      "reference_tool": reference_tool,
                      "reference_hook": reference_hook,
                      "reference_project": reference_project}, indent=2))
    return 0 if all(r["ok"] for r in replayed) else 1


def cmd_verify(args) -> int:
    root = os.path.abspath(args.root)
    state_file = os.path.join(root, ".agent-lab", "state.json")
    track, installed = args.track, []
    if os.path.exists(state_file):
        try:
            with open(state_file) as fh:
                state = json.load(fh)
            track = track or state.get("track")
            installed = (state.get("progress") or {}).get("installed_files") or []
        except (OSError, ValueError):
            pass
    if not track:
        sys.exit("no track known — pass --track or run /lab:start first")

    applied = (state.get("progress") or {}).get("applied_stages") or [] \
        if os.path.exists(state_file) else []

    if not installed and not applied:
        # Nothing has been installed yet, so there is nothing to be missing. Saying
        # "7 files missing" here sends a participant to catchup on their first minute.
        print(json.dumps({
            "track": track, "root": root, "intact": True,
            "checked_against": "nothing installed yet — the lab has not staged anything",
            "expected": 0, "missing": [], "git": os.path.isdir(os.path.join(root, ".git")),
            "next": "run /lab:next to begin",
        }, indent=2))
        return 0

    expected = installed or payload_files(track)
    basis = ("what the lab has installed so far" if installed
             else "the track's full payload")

    missing = [f for f in expected if not os.path.exists(os.path.join(root, f))]
    has_git = os.path.isdir(os.path.join(root, ".git"))

    print(json.dumps({
        "track": track,
        "root": root,
        "intact": not missing and has_git,
        "checked_against": basis,
        "expected": len(expected),
        "missing": missing,
        "git": has_git,
    }, indent=2))
    return 0 if (not missing and has_git) else 1


def main() -> int:
    ap = argparse.ArgumentParser(description="Agent Lab workspace")
    ap.add_argument("--root", default=os.getcwd(), help="lab root (default: cwd)")
    sub = ap.add_subparsers(dest="cmd", required=True)

    p = sub.add_parser("setup")
    p.add_argument("--track", required=True)
    p.add_argument("--force", action="store_true")
    p.set_defaults(fn=cmd_setup)

    p = sub.add_parser("catchup")
    p.add_argument("--with-reference", action="store_true",
                   help="also install the track's reference skill (the answer key)")
    p.set_defaults(fn=cmd_catchup)

    p = sub.add_parser("verify")
    p.add_argument("--track", default=None)
    p.set_defaults(fn=cmd_verify)

    p = sub.add_parser("stage")
    p.add_argument("stage_id")
    p.add_argument("--track", default=None)
    p.set_defaults(fn=cmd_stage)

    p = sub.add_parser("manifest")
    p.add_argument("--track", required=True)
    p.add_argument("--json", action="store_true", dest="as_json")
    p.set_defaults(fn=cmd_manifest)

    args = ap.parse_args()
    return args.fn(args)


if __name__ == "__main__":
    sys.exit(main())
